databases:
  - name: traveloffers-db
    plan: free
    databaseName: traveloffers
    user: traveloffers

services:
  - type: web
    name: traveloffers-web
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn traveloffers.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: traveloffers-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
